#!/usr/bin/env bash

function quiet () {
  "$@" > /dev/null 2>&1
}

function die {
  if [ ! "$1" = 0 ]; then
    echo "$2 - please report (https://discord.gg/YPV32gKCsH)" && exit 1
  fi
}

quiet command -v git
die $? "not ok - missing build tools, try installing git"

echo "#   __   ___  ___      ___ ____ "
echo "#  /__  /  / /   /_/  /__   /   "
echo "#  __/ /__/ /__ /  \\ /__   /  "
echo "# "
echo "# getting files..."
quiet git clone --depth=1 https://github.com/socketsupply/socket.git socket
cd socket || exit

source ./bin/clean.sh
source ./bin/install.sh "$1" "$2"
